os: linux
dist: xenial
language: php
php: nightly

install:
  - composer install --prefer-dist

before_script:
  - cp .env.example .env
  - php artisan key:generate

script:
  - php vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
